### ISSUE TITLE
Picking video in the simulator

### ISSUE THREAD

**Issue by darxmac** [jibon57/nativescript-mediafilepicker#48]
I tried setting up the plugin to pick video and ran it on a simulator, but the app and plugin crashes. To verify that I didn't do anything wrong, I tried running the demo app from the repo in the simulator and it crashes with the same error:

```

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.vincent.filepicker.activity.VideoPickActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at com.vincent.filepicker.activity.VideoPickActivity.initView(VideoPickActivity.java:108)
	at com.vincent.filepicker.activity.VideoPickActivity.onCreate(VideoPickActivity.java:78)
	at android.app.Activity.performCreate(Activity.java:6975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 9 more
```

Is that just a limited of the plugin when running in the simulator, or is there a workaround ? 

(I have not yet tried running a a real device, but I hope it works there although it would be nice to be able to debug on the simulator)

**Comment by jibon57** [comment]
Hi,
Looks like it didn't find the path of the file. Did you try with removing platform?
Thanks

**Comment by markkorput** [comment]
Having similar issue, removing platform and starting with a newly created android emulator did not help. Both emulators on which this occurs use API 30. Did not have the same issue with emulators running API 27 or 28.

It relates to a bug in the android filepicker library, specifically [this line](https://github.com/fishwjy/MultiType-FilePicker/blob/fbbcdbde53c0c8795c754e90c6c5f6c620976e43/filepicker/src/main/java/com/vincent/filepicker/activity/VideoPickActivity.java#L103) which doesn't check if `getExternalCacheDir()` returns null, which is what seems to happen. This is [according to the android developer documentation](https://developer.android.com/reference/android/content/Context#getExternalCacheDir()) expected behaviour when shared storage is not available.

Error log (on android emulator with API 30):
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{<APP_ID>/com.vincent.filepicker.activity.VideoPickActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{<APP_ID>/com.vincent.filepicker.activity.VideoPickActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:223)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
System.err: 	at com.vincent.filepicker.activity.VideoPickActivity.initView(VideoPickActivity.java:108)
System.err: 	at com.vincent.filepicker.activity.VideoPickActivity.onCreate(VideoPickActivity.java:78)
System.err: 	at android.app.Activity.performCreate(Activity.java:7995)
System.err: 	at android.app.Activity.performCreate(Activity.java:7979)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
System.err: 	... 11 more
```
